#!/bin/sh /etc/rc.common

START=70
STOP=12

USE_PROCD=1
NAME=inbd
PROG=/usr/bin/inbd

start_service() {
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn "5" "0" "3"
	procd_close_instance
}

