#!/bin/sh /etc/rc.common
#
# Copyright (C) 2009 OpenWrt.org
#

START=70
STOP=12

USE_PROCD=1
NAME=inbd
PROG=/usr/bin/inbd



start_service() {

	procd_open_instance
	procd_set_param command $PROG --app
	procd_set_param respawn "5" "0" "3"
	procd_close_instance
}

stop_service() {

	killall -q $NAME
}

reload_service() {
	killall -q $NAME
	start
}

service_triggers()
{
	procd_add_reload_trigger inbd
}

boot() {
	start
}
